Topics covered:

Groupby Object
*   Applying built-in aggregation fuctions on groupby objects
*   GroupBy Attributes and Methods
*   agg method
*   Looping on groups
*   apply method
*   groupby on multiple columns

In [3]:
import numpy as np
import pandas as pd

In [4]:
movies = pd.read_csv('/content/imdb-top-1000.csv')
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

## GroupBy Object

Created groups on the basis of categorical data.

In [3]:
movies.groupby('Genre')  # grouping on the basis of Genre

In [7]:
genres = movies.groupby('Genre')

### Applying builtin aggregation fuctions on groupby objects

We can apply any aggregation functions such as sum, mean, min, max, count etc on groupby object. It will give dataframe which contains aggregated value of columns for each group.

In [19]:
# Applying builtin aggregation fuctions on groupby objects - sum, mean, min, max, median, std, var, mode, count
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [20]:
type(genres.min())

pandas.core.frame.DataFrame

In [21]:
genres.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [22]:
genres.mean(numeric_only=True)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [29]:
# find the top 3 genres by total earning
genres.sum(numeric_only=True)['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [30]:
genres['Gross'].sum().sort_values(ascending=False).head(3)  # this is faster - use this approach in future

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [35]:
# find the genre with highest avg IMDB rating
genres['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [40]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1).index[0]

'Christopher Nolan'

In [42]:
# find number of movies done by each actor
movies['Star1'].value_counts()

Star1
Tom Hanks          12
Robert De Niro     11
Al Pacino          10
Clint Eastwood     10
Humphrey Bogart     9
                   ..
Preity Zinta        1
Javier Bardem       1
Ki-duk Kim          1
Vladimir Garin      1
Robert Donat        1
Name: count, Length: 660, dtype: int64

In [45]:
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

### GroupBy Attributes and Methods


*   len
*   size
*   first, last, nth
*   get_group
*   groups
*   describe
*   sample
*   nunique

**len**

In [46]:
genres

In [47]:
# len - gives total number of groups
len(genres)

14

In [48]:
movies['Genre'].nunique()

14

**size**

In [49]:
# size - gives no. of items in each group
genres.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [50]:
movies['Genre'].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

**first(), last(), nth()**

In [51]:
genres.first()  # gives first row of each group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [52]:
genres.last()  # gives last row of each group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [53]:
genres.nth(6)   # to get nth row of each group if present

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

**get_group**

In [54]:
# get_group -> to get all records of a group
genres.get_group('Fantasy')   # faster than filtering

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [56]:
movies[movies['Genre'] == 'Fantasy']

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

**groups**

In [57]:
genres.groups  # gives dictionary of groups -> value: all index position of a group

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

**describe**

In [58]:
genres.describe()  # gives summary of each group for numeric columns

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

**sample**

In [59]:
genres.sample()  # gives one random row of each group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
888,Baby Driver,2017,113,Action,7.6,Edgar Wright,Ansel Elgort,439406,107825862.0,86.0
273,Fitzcarraldo,1982,158,Adventure,8.1,Werner Herzog,Klaus Kinski,31595,616558047.0,NaN
510,Cowboy Bebop: Tengoku no tobira,2001,115,Animation,7.9,Shin'ichirô Watanabe,Tensai Okamura,42897,1000045.0,61.0
632,The World's Fastest Indian,2005,127,Biography,7.8,Roger Donaldson,Anthony Hopkins,51980,5128124.0,68.0
786,Good Bye Lenin!,2003,121,Comedy,7.7,Wolfgang Becker,Daniel Brühl,137981,4064200.0,68.0
611,Män som hatar kvinnor,2009,152,Crime,7.8,Niels Arden Oplev,Michael Nyqvist,208994,10095170.0,76.0
772,Zwartboek,2006,145,Drama,7.7,Paul Verhoeven,Carice van Houten,72643,4398392.0,71.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [60]:
genres.sample(2)   # error - due to less no. of rows in some groups : use replace=True

ValueError: Cannot take a larger sample than population when 'replace=False'

In [61]:
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
532,The Blues Brothers,1980,133,Action,7.9,John Landis,John Belushi,183182,57229890.0,60.0
357,The Avengers,2012,143,Action,8.0,Joss Whedon,Robert Downey Jr.,1260806,623279547.0,69.0
604,Captain Phillips,2013,134,Adventure,7.8,Paul Greengrass,Tom Hanks,421244,107100855.0,82.0
681,The Goonies,1985,114,Adventure,7.8,Richard Donner,Sean Astin,244430,61503218.0,62.0
740,Wreck-It Ralph,2012,101,Animation,7.7,Rich Moore,John C. Reilly,380195,189422889.0,72.0
358,Persepolis,2007,96,Animation,8.0,Vincent Paronnaud,Marjane Satrapi,88656,4445756.0,90.0
759,Changeling,2008,141,Biography,7.7,Clint Eastwood,Angelina Jolie,239203,35739802.0,63.0
910,Moneyball,2011,133,Biography,7.6,Bennett Miller,Brad Pitt,369529,75605492.0,87.0
464,Dil Bechara,2020,101,Comedy,7.9,Mukesh Chhabra,Sushant Singh Rajput,111478,228629261.0,NaN
660,The Sandlot,1993,101,Comedy,7.8,David Mickey Evans,Tom Guiry,78963,32416586.0,55.0
546,In the Heat of the Night,1967,110,Crime,7.9,Norman Jewison,Sidney Poitier,67804,24379978.0,75.0
441,The Killing,1956,84,Crime,8.0,Stanley Kubrick,Sterling Hayden,81702,309154156.0,91.0
259,Before Sunrise,1995,101,Drama,8.1,Richard Linklater,Ethan Hawke,272291,5535405.0,77.0
253,Fa yeung nin wah,2000,98,Drama,8.1,Kar-Wai Wong,Tony Chiu-Wai Leung,124383,2734044.0,85.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

**nunique**

In [62]:
genres.nunique()  # gives no. of unique values in each group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

### agg method

In [64]:
genres.sum(numeric_only=True)
# apply sum on each numeric column, but suppose we want different aggregation operations on different columns -> use agg method

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [68]:
# agg method
# passing dict
genres.agg({
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    'No_of_Votes':'sum',
    'Gross':'sum',
    'Metascore':'max'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       98.0
Adventure  134.111111     7.937500     22576163  9.496922e+09      100.0
Animation   99.585366     7.930488     21978630  1.463147e+10       96.0
Biography  136.022727     7.938636     24006844  8.276358e+09       97.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       99.0
Crime      126.392523     8.016822     33533615  8.452632e+09      100.0
Drama      124.737024     7.957439     61367304  3.540997e+10      100.0
Family     107.500000     7.800000       551221  4.391106e+08       91.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       97.0
Horror     102.090909     7.909091      3742556  1.034649e+09       97.0
Mystery    119.083333     7.975000      4203004  1.256417e+09      100.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       90.0

In [93]:
# passing list of functions
genres.agg(['min','max','mean','sum'])

TypeError: agg function failed [how->mean,dtype->object]

In [74]:
# Adding both the syntax
genres.agg(
    {
        'Runtime':['min','mean'],
        'IMDB_Rating':'mean',
        'No_of_Votes':['sum','max'],
        'Gross':'sum',
        'Metascore':'min'
    }
)

          Runtime             IMDB_Rating No_of_Votes                  Gross  \
              min        mean        mean         sum      max           sum
Genre
Action         45  129.046512    7.949419    72282412  2303232  3.263226e+10
Adventure      88  134.111111    7.937500    22576163  1512360  9.496922e+09
Animation      71   99.585366    7.930488    21978630   999790  1.463147e+10
Biography      93  136.022727    7.938636    24006844  1213505  8.276358e+09
Comedy         68  112.129032    7.901290    27620327   939631  1.566387e+10
Crime          80  126.392523    8.016822    33533615  1826188  8.452632e+09
Drama          64  124.737024    7.957439    61367304  2343110  3.540997e+10
Family        100  107.500000    7.800000      551221   372490  4.391106e+08
Fantasy        76   85.000000    8.000000      146222    88794  7.827267e+08
Film-Noir     100  104.000000    7.966667      367215   158731  1.259105e+08
Horror         71  102.090909    7.909091     3742556   787806  1.034649e+09
Mystery        96  119.083333    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108.000000    7.800000       27733    27733  1.755074e+07
Western       132  148.250000    8.350000     1289665   688390  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

### Looping on Groups

In [95]:
# looping on groups
for group,data in genres:
  print(type(group),type(data))

<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>
<class 'str'> <class 'pandas.core.frame.DataFrame'>

When we loop groupby object, it will give two things:

1.   group - string eg. genre name
2.   data - which is dataframe contains all data of a group

In [98]:
for group,data in genres:
  print(group)

Action
Adventure
Animation
Biography
Comedy
Crime
Drama
Family
Fantasy
Film-Noir
Horror
Mystery
Thriller
Western

In [97]:
for group,data in genres:
  print(data)

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0

In [126]:
# find the highest rated movie of each genre
df = pd.DataFrame()
# df = pd.DataFrame(columns=movies.columns)
for group,data in genres:
  temp = data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]
  df = pd.concat([df,temp])
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [148]:
def highest_rated(group):
  return group[group['IMDB_Rating'] == group['IMDB_Rating'].max()]

In [149]:
genres.apply(highest_rated)

                                      Series_Title Released_Year  Runtime  \
Genre
Action    2                        The Dark Knight          2008      152
Adventure 21                          Interstellar          2014      169
Animation 23         Sen to Chihiro no kamikakushi          2001      125
Biography 7                       Schindler's List          1993      195
Comedy    19                          Gisaengchung          2019      132
          26                       La vita è bella          1997      116
Crime     1                          The Godfather          1972      175
Drama     0               The Shawshank Redemption          1994      142
Family    688           E.T. the Extra-Terrestrial          1982      115
          698  Willy Wonka & the Chocolate Factory          1971      100
Fantasy   321         Das Cabinet des Dr. Caligari          1920       76
Film-Noir 309                        The Third Man          1949      104
Horror    49                                Psycho          1960      109
Mystery   69                               Memento          2000      113
          81                           Rear Window          1954      112
Thriller  700                      Wait Until Dark          1967      108
Western   12       Il buono, il brutto, il cattivo          1966      161

                   Genre  IMDB_Rating              Director  \
Genre
Action    2       Action          9.0     Christopher Nolan
Adventure 21   Adventure          8.6     Christopher Nolan
Animation 23   Animation          8.6        Hayao Miyazaki
Biography 7    Biography          8.9      Steven Spielberg
Comedy    19      Comedy          8.6          Bong Joon Ho
          26      Comedy          8.6       Roberto Benigni
Crime     1        Crime          9.2  Francis Ford Coppola
Drama     0        Drama          9.3        Frank Darabont
Family    688     Family          7.8      Steven Spielberg
          698     Family          7.8            Mel Stuart
Fantasy   321    Fantasy          8.1          Robert Wiene
Film-Noir 309  Film-Noir          8.1            Carol Reed
Horror    49      Horror          8.5      Alfred Hitchcock
Mystery   69     Mystery          8.4     Christopher Nolan
          81     Mystery          8.4      Alfred Hitchcock
Thriller  700   Thriller          7.8         Terence Young
Western   12     Western          8.8          Sergio Leone

                             Star1  No_of_Votes        Gross  Metascore
Genre
Action    2         Christian Bale      2303232  534858444.0       84.0
Adventure 21   Matthew McConaughey      1512360  188020017.0       74.0
Animation 23         Daveigh Chase       651376   10055859.0       96.0
Biography 7            Liam Neeson      1213505   96898818.0       94.0
Comedy    19          Kang-ho Song       552778   53367844.0       96.0
          26       Roberto Benigni       623629   57598247.0       59.0
Crime     1          Marlon Brando      1620367  134966411.0      100.0
Drama     0            Tim Robbins      2343110   28341469.0       80.0
Family    688         Henry Thomas       372490  435110554.0       91.0
          698          Gene Wilder       178731    4000000.0       67.0
Fantasy   321        Werner Krauss        57428  337574718.0        NaN
Film-Noir 309         Orson Welles       158731     449191.0       97.0
Horror    49       Anthony Perkins       604211   32000000.0       97.0
Mystery   69            Guy Pearce      1125712   25544867.0       80.0
          81         James Stewart       444074   36764313.0      100.0
Thriller  700       Audrey Hepburn        27733   17550741.0       81.0
Western   12        Clint Eastwood       688390    6100000.0       90.0

### apply method

Split -> Apply -> Combine Strategy

In [127]:
# split (apply) combine
# apply -> builtin function

genres.apply(min)

<ipython-input-127-05c828fb38c6>:4: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [128]:
genres.apply(np.minimum.reduce)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [145]:
# find number of movies starting with A for each group
def start_with_a(group):
  # return group[group['Series_Title'].str.startswith('A')]['Series_Title'].count()
  return group['Series_Title'].str.startswith('A').sum()

In [146]:
genres.apply(start_with_a)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [132]:
movies[movies['Series_Title'].str.startswith('A')].groupby('Genre').size()

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Horror        1
dtype: int64

In [147]:
movies[movies['Series_Title'].str.startswith('A')]['Genre'].value_counts()

Genre
Drama        21
Comedy       14
Action       10
Biography     9
Crime         4
Animation     2
Adventure     2
Horror        1
Name: count, dtype: int64

In [150]:
# find ranking of each movie in the group according to IMDB score
def genre_rank(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [151]:
genres.apply(genre_rank)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [152]:
# find normalized IMDB rating group wise
def normal_rank(group):
  group['normalized_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min()) / (group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

In [153]:
genres.apply(normal_rank)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalized_rating
Genre
Action   2             1.000000
         5             0.928571
         8             0.857143
         10            0.857143
         13            0.785714
...                         ...
Thriller 700                NaN
Western  12            1.000000
         48            0.700000
         115           0.500000
         691           0.000000

[1000 rows x 11 columns]

### Groupby on multiple columns

We can have groups on the basis of multiple columns.

In [12]:
movies.head(3)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0

In [7]:
# groupby on multiple columns
duo = movies.groupby(['Director','Star1'])
duo

In [9]:
# size
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [10]:
# get_group
duo.get_group(('Christopher Nolan','Christian Bale'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [14]:
# find the most earning actor->director combo
movies.groupby(['Director','Star1'])['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [18]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Genre'])['Metascore'].mean().sort_values(ascending=False).head(1)

Star1           Genre
Ellar Coltrane  Drama    100.0
Name: Metascore, dtype: float64

In [24]:
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(1)

              Star1  Genre  Metascore
230  Ellar Coltrane  Drama      100.0

**agg on multiple groupby**

In [29]:
# agg on multiple groupby
duo.agg(
    {
        'Runtime':['mean','min','max'],
        'IMDB_Rating':['mean','min','max'],
        'Gross':['sum','mean','max','min']
    }
).sample(5)

                               Runtime           IMDB_Rating            \
                                  mean  min  max        mean  min  max
Director       Star1
Brian De Palma Al Pacino         157.0  144  170         8.1  7.9  8.3
Billy Wilder   Humphrey Bogart   113.0  113  113         7.7  7.7  7.7
Hayao Miyazaki Kirsten Dunst     103.0  103  103         7.8  7.8  7.8
Zoya Akhtar    Vijay Varma       154.0  154  154         8.0  8.0  8.0
Yash Chopra    Shah Rukh Khan    192.0  192  192         7.8  7.8  7.8

                                      Gross                            \
                                        sum         mean          max
Director       Star1
Brian De Palma Al Pacino         82547304.0   41273652.0   45598982.0
Billy Wilder   Humphrey Bogart  199534614.0  199534614.0  199534614.0
Hayao Miyazaki Kirsten Dunst     58564351.0   58564351.0   58564351.0
Zoya Akhtar    Vijay Varma        5566534.0    5566534.0    5566534.0
Yash Chopra    Shah Rukh Khan     2921738.0    2921738.0    2921738.0


                                        min
Director       Star1
Brian De Palma Al Pacino         36948322.0
Billy Wilder   Humphrey Bogart  199534614.0
Hayao Miyazaki Kirsten Dunst     58564351.0
Zoya Akhtar    Vijay Varma        5566534.0
Yash Chopra    Shah Rukh Khan     2921738.0

### Exercise

In [31]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [32]:
ipl.shape

(179078, 21)

In [33]:
# find the top 10 batsman in terms of runs
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [38]:
# find the batsman with max no of sixes
ipl[ipl['batsman_runs'] == 6]['batsman'].value_counts().head(1)

batsman
CH Gayle    327
Name: count, dtype: int64

In [39]:
ipl[ipl['batsman_runs'] == 6].groupby('batsman').size().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
dtype: int64

In [47]:
# find batsman with most number of 4's and 6's in last 5 overs
m1 = ipl['over']>15
m2 = ipl['batsman_runs'].isin([4,6])
ipl[m1 & m2]['batsman'].value_counts().head(1).index[0]

'MS Dhoni'

In [50]:
# ipl[m1 & m2].groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(1).index[0]
ipl[m1 & m2].groupby('batsman').size().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

In [51]:
# find V Kohli's record against all teams
df = ipl[ipl['batsman'] == 'V Kohli']
df.groupby('bowling_team')['batsman_runs'].sum()

bowling_team
Chennai Super Kings        749
Deccan Chargers            306
Delhi Capitals              66
Delhi Daredevils           763
Gujarat Lions              283
Kings XI Punjab            636
Kochi Tuskers Kerala        50
Kolkata Knight Riders      675
Mumbai Indians             628
Pune Warriors              128
Rajasthan Royals           370
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        509
Name: batsman_runs, dtype: int64

In [64]:
# Create a function that can return the highest score of any batsman
def highest_score(name):
  df_batter = ipl[ipl['batsman'] == name]
  return df_batter.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [67]:
name = input('Enter batsman name: ')
highest_score(name)

Enter batsman name: CH Gayle

175

In [109]:
# find batsman record against all teams -> total runs, highest score, no of 4s, no of 6s
def record(group):
  group['total_runs']= group['batsman_runs'].sum()
  group['highest_score'] = group.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]
  group['no_of_4'] = (group['batsman_runs']==4).sum()
  group['no_of_6'] = (group['batsman_runs']==6).sum()
  return group[['total_runs','highest_score','no_of_4','no_of_6']].drop_duplicates()

In [121]:
df = ipl[ipl['batsman'] == 'MS Dhoni']
df.groupby('bowling_team').apply(record)

,,total_runs,highest_score,no_of_4,no_of_6
bowling_team,,,,,
Deccan Chargers,19832,281,58,22,6
Delhi Capitals,165894,89,45,7,3
Delhi Daredevils,2058,488,63,29,26
Gujarat Lions,2907,83,30,5,4
Kings XI Punjab,764,601,83,44,31
Kochi Tuskers Kerala,59546,23,14,2,1
Kolkata Knight Riders,6766,474,66,29,20
Mumbai Indians,469,669,63,48,30
Pune Warriors,61892,135,45,10,5
Rajasthan Royals,19377,428,79,25,16
Royal Challengers Bangalore,3869,808,89,46,44
Sunrisers Hyderabad,5953,398,67,30,21

In [130]:
res = pd.DataFrame()
for group,data in df.groupby('bowling_team'):
  total_runs = data['batsman_runs'].sum()
  highest_score= data.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]
  no_of_4 = (data['batsman_runs']==4).sum()
  no_of_6 = (data['batsman_runs']==6).sum()
  temp = pd.DataFrame(data={'Total Runs':total_runs,'Highest Score':highest_score,'Total 4s':no_of_4,'Total 6s':no_of_6},index=[group])
  res = pd.concat([res,temp])
res

                             Total Runs  Highest Score  Total 4s  Total 6s
Deccan Chargers                     281             58        22         6
Delhi Capitals                       89             45         7         3
Delhi Daredevils                    488             63        29        26
Gujarat Lions                        83             30         5         4
Kings XI Punjab                     601             83        44        31
Kochi Tuskers Kerala                 23             14         2         1
Kolkata Knight Riders               474             66        29        20
Mumbai Indians                      669             63        48        30
Pune Warriors                       135             45        10         5
Rajasthan Royals                    428             79        25        16
Royal Challengers Bangalore         808             89        46        44
Sunrisers Hyderabad                 398             67        30        21